---
- name: This playbook installs httpd package and start service
  hosts: webservers
  become: true
  tasks:
  - name: Installing httpd package
    yum:
      name: httpd
      state: installed
    notify: Starting httpd service

  handlers:
  - name: Starting httpd service
    service:
      name: httpd
      state: started
