---
- name: Setup tomcat
  hosts: all
  become: true
  tasks:
  - name: Install java on RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"
 
  - name: Install java on Debian
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: Download tomcat
    get_url:
      url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.46/bin/apache-tomcat-9.0.46.tar.gz
      dest: /opt

  - name: Extract tomcat package
    unarchive:
      src: /opt/apache-tomcat-9.0.46.tar.gz
      dest: /opt
      remote_src: True

  - name: Give exec permissions
    file:
      path: /opt/apache-tomcat-9.0.46/bin/startup.sh
      mode: 0777

  - name: Start Tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-9.0.46/bin

